# Generated by Django 5.2.5 on 2025-08-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_image_comment_follow_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
